### ISSUE TITLE
fateboard 1.5 unable to display diagram

### ISSUE THREAD

**Issue by cometta** [FederatedAI/FATE-Board#72]
I run on a standalone mode, i able to run jobs successfully. Log are showing up in the fateboard, but i can't see the dashboard diagrams. There is no error in browser console. Any idea why?

![image](https://user-images.githubusercontent.com/187495/98516687-c7172e00-22a7-11eb-9d38-1dd34edc12cc.png)

**Comment by cometta** [comment]
issued resolved. modify service_conf file like below
```
fateflow:
  # you must set real ip address or 127.0.0.1, 0.0.0.0 is not supported
  host: python
  http_port: 9380
  grpc_port: 9360
  # support rollsite or nginx as a coordinate proxy, rollsite recommended in the fate on eggroll, nginx is recommended in the fate on spark
  # format(proxy: rollsite) means rollsite use the rollsite configuration of fate_one_eggroll and nginx use the nginx configuration of fate_one_spark
  # you can customize the config by format(proxy:\n name: rollsite \n host: xx \n port: xx)
  proxy: rollsite
fateboard:
  host: fateboard
  port: 8080
```
